### ISSUE TITLE
Will using std::mpsc::channel or std::atomic::AtomicBool break loom?

### ISSUE THREAD

**Issue by atroche** [carllerche/loom#10]
I'm getting a hanging test that uses `loom::fuzz` (testing code that uses channels / `AtomicBool`), and I'm wondering if it's a problem in my code, or just a current limitation of the library.

I've replaced all my uses of `Arc`, `Mutex` and `spawn` with loom's versions.

**Comment by carllerche** [comment]
I can definitely say that the answer is: maybe.

In short, you need to use loom variants of all types that could impact the concurrent execution. This includes atomics and channels. Odds are you will need to use loom variants of these types.

I assume you ask because loom does not provide versions of these types yet. I would take a PR to add them. Adding `AtomicBool` should be trivial (copy [this](https://github.com/carllerche/loom/blob/master/src/sync/atomic/usize.rs) and replace `usize` with `bool`). For `channel`, it should be sufficient to provide a version that is backed by a loom `Mutex`, `Condvar`, and `VecDeque<T>`.

Now, if you are using the channel / AtomicBool for something tangential to the behavior being tested, then it might be fine to use the `std` versions (but probably not).

**Comment by atroche** [comment]
Thanks, that's very clear.

**Comment by carllerche** [comment]
np

**Comment by rw** [comment]
@atroche @carllerche Following up, could you share the channel code you wrote that uses `Mutex`, `CondVar`, and `VecQueue<T>`?
